"""
Dockrion Generated Runtime
==========================
Agent: invoice-serviceMode: Handler (direct callable)
Handler: app.service:process_invoiceDescription: Invoice processing service with custom handler logic.

Auto-generated by Dockrion SDK v1.0.0
Do not edit manually - regenerate using `dockrion build`
"""
import sys
from pathlib import Path

# Add project root to Python path for agent module imports
# We need to find the directory that contains the agent's top-level module
current_dir = Path(__file__).parent
project_root = current_dir.parent

# For handlers/entrypoints in nested directories (e.g., examples/agent_name/),
# we need to find the actual project root by looking for the top-level module
handler_module = "app.service:process_invoice".split(":")[0]
top_level_module = handler_module.split(".")[0]

# Walk up the directory tree to find where the top-level module exists
max_levels = 5  # Safety limit to prevent infinite loops
for _ in range(max_levels):
    if (project_root / top_level_module).exists():
        break
    if project_root.parent == project_root:  # Reached filesystem root
        break
    project_root = project_root.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from dockrion_runtime import create_app
from dockrion_schema import DockSpec

# ============================================================================
# Agent Specification (Embedded from Dockfile.yaml)
# ============================================================================

SPEC_DATA = {'version': '1.0', 'agent': {'name': 'invoice-service', 'description': 'Invoice processing service with custom handler logic.', 'handler': 'app.service:process_invoice', 'framework': 'custom'}, 'model': {'provider': 'openai', 'name': 'gpt-4o-mini', 'temperature': 0.2, 'max_tokens': 1500, 'extra': {}}, 'io_schema': {'input': {'type': 'object', 'properties': {'document_text': {'type': 'string', 'description': 'Invoice text to process'}, 'currency_hint': {'type': 'string', 'description': 'Expected currency (INR, USD, EUR)'}, 'vendor_hint': {'type': 'string', 'description': 'Known vendor name'}, 'user_id': {'type': 'string', 'description': 'User ID for tracking'}}, 'required': ['document_text']}, 'output': {'type': 'object', 'properties': {'vendor': {'type': 'string'}, 'invoice_number': {'type': 'string'}, 'invoice_date': {'type': 'string'}, 'total_amount': {'type': 'number'}, 'currency': {'type': 'string'}, 'line_items': {'type': 'array', 'items': {'type': 'object', 'properties': {'description': {'type': 'string'}, 'quantity': {'type': 'number'}, 'unit_price': {'type': 'number'}, 'amount': {'type': 'number'}}}}, 'processing_metadata': {'type': 'object'}, 'success': {'type': 'boolean'}}, 'required': ['vendor', 'invoice_number', 'success']}}, 'arguments': {'timeout_sec': 30}, 'auth': {'mode': 'api_key', 'api_keys': {'env_var': 'MY_AGENT_KEY', 'header': 'X-API-Key', 'allow_bearer': True, 'enabled': True, 'rotation_days': 30}, 'roles': [], 'rate_limits': {}}, 'expose': {'rest': True, 'streaming': 'none', 'port': 8080, 'host': '0.0.0.0', 'cors': {'origins': ['*'], 'methods': ['GET', 'POST', 'OPTIONS']}}, 'metadata': {'maintainer': 'Dockrion Team', 'version': 'v1.0.0', 'tags': ['handler-example', 'invoice', 'service']}}

# ============================================================================
# Create Application
# ============================================================================

# Parse and validate the embedded specification
spec = DockSpec.model_validate(SPEC_DATA)

# Create the FastAPI application using the runtime factory# Handler mode: direct callable function
app = create_app(
    spec=spec,
    agent_handler="app.service:process_invoice"
)
# ============================================================================
# Main Entry Point
# ============================================================================

if __name__ == "__main__":
    import uvicorn
    
    host = "0.0.0.0"
    port = 8080
    
    print(f"🚀 Starting invoice-service on {host}:{port}")
    uvicorn.run(
        app,
        host=host,
        port=port,
        log_level="info"
    )
